version: '3'
services:
  zookeeper:
    container_name: zookeeper-compose
    image: debezium/zookeeper:1.2
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    container_name: kafka-compose
    image: debezium/kafka:1.2
    links:
      - zookeeper:zookeeper
    environment:
      ZOOKEEPER_CONNECT: ${HOST}
    ports:
      - 9092:9092
    env_file: .env
  postgres:
    container_name: postgres-kafka-tutorial
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
  connect:
    container_name: connect-compose
    image: debezium/connect:1.2
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: "${HOST}:9092"
    links:
      - zookeeper:zookeeper
      - kafka:kafka
      - postgres:postgres
    ports:
      - 8083:8083
    env_file: .env
